
// This file was auto-generated by ML.NET Model Builder. 

using MLModel1_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    UserID = 1F,
    Month = 2F,
    Days_Worked = 19F,
    Total_Working_Days = 28F,
};

// Make a single prediction on the sample data and print results
var predictionResult = MLModel1.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Attendance_Percentage with predicted Attendance_Percentage from sample data...\n\n");


Console.WriteLine($"UserID: {1F}");
Console.WriteLine($"Month: {2F}");
Console.WriteLine($"Days_Worked: {19F}");
Console.WriteLine($"Total_Working_Days: {28F}");
Console.WriteLine($"Attendance_Percentage: {0.68F}");


Console.WriteLine($"\n\nPredicted Attendance_Percentage: {predictionResult.Score}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

