﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace EMS___SCNE
{
    public partial class MLModel1
    {
        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"UserID", @"UserID"),new InputOutputColumnPair(@"Month", @"Month"),new InputOutputColumnPair(@"Days_Worked", @"Days_Worked"),new InputOutputColumnPair(@"Total_Working_Days", @"Total_Working_Days")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"UserID",@"Month",@"Days_Worked",@"Total_Working_Days"}))      
                                    .Append(mlContext.Transforms.NormalizeMinMax(@"Features", @"Features"))      
                                    .Append(mlContext.Regression.Trainers.FastTreeTweedie(new FastTreeTweedieTrainer.Options(){NumberOfLeaves=21,MinimumExampleCountPerLeaf=3,NumberOfTrees=3863,MaximumBinCountPerFeature=194,FeatureFraction=0.938749176701226,LearningRate=0.0038944452174552,LabelColumnName=@"Attendance_Percentage",FeatureColumnName=@"Features"}));

            return pipeline;
        }
    }
}
